import { Layout } from '@layouts/index'

const TiempoDeEntrega = () => {
  return (
    <Layout title='Terminos del servicio' variant='docs'>
      <p className='typo-p'>Entre el cliente y/o usuario, quien actúa directamente, si es una persona natural o una persona jurídica, y otro lado Manos felices., sociedad comercial debidamente constituida bajo las leyes colombianas, que cuenta con un sitio web manosfelices.co celebran el presente contrato de conformidad con los términos y condiciones exigidos por la ley colombiana.<br /><br />La información y datos personales suministrados por el cliente, consumidor, o cualquier usuario, se presume auténtico y veraz.<br /><br />En caso de tratarse de una persona jurídica, natural o actuar en nombre o representación de un tercero, el suscriptor declara que está legalmente facultado para actuar en nombre y representación del tercero manteniendo indemne a Manos felices de cualquier responsabilidad por suplantación personal que realice cualquier cliente y/o usuario.<br /><br /><strong>PARÁGRAFO PRIMERO:</strong> Para realizar cualquier compra, es requisito esencial registrarse, identificarse y presentarse como usuario en la página web, actividades que se realizan por medio de una cuenta de correo electrónico y una clave secreta del cliente, la cual es de carácter personal, intransferible y de responsabilidad exclusiva y excluyente del cliente.<br /><br /><strong>PARÁGRAFO SEGUNDO:</strong> Es responsabilidad del cliente cualquier uso que de la clave suministrada se realice, la cual no podrá ser transferida o revelada a terceros bajo ningún motivo. Así mismo, el cliente deberá adoptar todas las medidas de seguridad necesarias para evitar el mal uso o el conocimiento de esta por parte de terceros. Se recomienda efectuar el cambio de clave de manera periódica.<br /><br /><strong>PARÁGRAFO TERCERO:</strong> En caso de pérdida, olvido o exposición a terceros de la clave, deberá remitirse a la sección de autenticación del sitio en donde hay un link recordar contraseña, en donde siguiendo las instrucciones, el cliente podrá recuperar su contraseña, a través de su correo electrónico o cambiar la clave. Si por algún motivo no logra solucionar el inconveniente debe escribir al e-mail: info@manosfelices.co</p>
      <h2 className='typo-h3'>1. La actividad</h2>
      <p className='typo-p'>Manos felices, pondrá a disposición de los clientes, los colores en los que pueden adquirir los productos. Estos se exhibirán de la manera más real posible, sin embargo, hay que tener en cuenta que con cada equipo/computador se puede visualizar diferente, por lo que la empresa no se hace responsable de este hecho.</p>
      <h2 className='typo-h3'>2. Aceptación de los términos</h2>
      <p className='typo-p'>El usuario declara y acepta haber leído y entendido estos Términos de Uso y está de acuerdo en sujetarse a los mismos y cumplir con todas las leyes y reglamentos aplicables que hagan parte de la Legislación Colombiana.<br /><br />Cuando el usuario utilice cualquier servicio suministrado en este Sitio, estará sujeto a las reglas, guías, políticas, términos y condiciones aplicables a dicho servicio en particular. Manos felices. no se responsabiliza de que el material en este sitio sea apropiado o esté disponible para su uso en otros lugares, estando prohibido su acceso desde territorios donde su contenido sea ilegal.</p>
    </Layout>
  )
}

export default TiempoDeEntrega
